### ISSUE TITLE
Problems in visualising dataset

### ISSUE THREAD

**Issue by elenapalmisano** [routetopa/tet#13]
When making the query http://prato-tet.routetopa.eu/it/search/?query=parlamento
and click on the name "Risultati Rinnovo parlamento Europeo 2014"
I get the following page of errors:
http://prato-tet.routetopa.eu/it/dataset/5ea6ff51-6eab-4201-b7d9-030101e8db2b

**Comment by waqarini** [comment]
The issue is being caused by column name "NUOVO CENTRO DESTRA (NCD)  - UNIONE DEI DEMOCRATICI CRISTIANI E DEMOCRATICI DI CENTRO" . CKAN DataStore API has a [limitation](https://github.com/ckan/ckan/issues/2804) that the column header can't contain more than 63 characters , you can  fix this by making sure that column headers names in dataset are limited to 63 characters only.
